<?php

namespace Pheanstalk\Structure;

use Doctrine\Common\Collections\ArrayCollection;
use PHPUnit\Framework\TestCase;

class JobInstanceTest extends TestCase
{
    /** @var JobInstance $jobInstance */
    protected $jobInstance;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->jobInstance = new JobInstance(new ArrayCollection([]));
    }

    public function testTaskInstances()
    {
        $this->assertTrue($this->jobInstance->getTaskInstances()->isEmpty());
        $task = new TaskInstance([]);
        $this->jobInstance->setTaskInstances(new ArrayCollection([$task]));
        $this->assertSame($task, $this->jobInstance->getTaskInstances()->first());
        $this->jobInstance->removeTaskInstance($task);
        $this->assertTrue($this->jobInstance->getTaskInstances()->isEmpty());
        $this->jobInstance->addTaskInstance($task);
        $this->assertSame($task, $this->jobInstance->getTaskInstances()->first());
        $this->jobInstance->removeTaskInstance($task);
        $this->assertTrue($this->jobInstance->getTaskInstances()->isEmpty());
    }
}
