<?php

namespace Pheanstalk\Structure;

use Doctrine\Common\Collections\ArrayCollection;
use PHPUnit\Framework\TestCase;

class JobTest extends TestCase
{
    /** @var Job $object */
    protected $object;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->object = new Job(new ArrayCollection([]));
    }

    public function testTasks()
    {
        $this->assertTrue($this->object->getTasks()->isEmpty());
        $task = new Task('/bin/echo test', Tube::SCHEDULER_TYPE_DEFAULT);
        $this->object->setTasks(new ArrayCollection([$task]));
        $this->assertSame($task, $this->object->getTasks()->first());
        $this->object->removeTask($task);
        $this->assertTrue($this->object->getTasks()->isEmpty());
        $this->object->addTask($task);
        $this->assertSame($task, $this->object->getTasks()->first());
        $this->object->removeTask($task);
        $this->assertTrue($this->object->getTasks()->isEmpty());
    }
}
