<?php

namespace Pheanstalk\Structure;

use PHPUnit\Framework\TestCase;

class TaskTest extends TestCase
{

    /** @var Task $object */
    protected $object;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->object = new Task('/bin/echo test', Tube::SCHEDULER_TYPE_DEFAULT);
    }

    public function testOutputMethod()
    {
        $this->object->setOutputMethod('1');
        $this->assertSame('1', $this->object->getOutputMethod());
    }

    public function testParametersMode()
    {
        $this->object->setParametersMode('1');
        $this->assertSame('1', $this->object->getParametersMode());
    }

    public function testPath()
    {
        $this->object->setPath('1');
        $this->assertSame('1', $this->object->getPath());
    }

    public function testQueue()
    {
        $this->object->setQueue('1');
        $this->assertSame('1', $this->object->getQueue());
    }

    public function testHost()
    {
        $this->assertNull($this->object->getHost());
        $this->object->setHost('1');
        $this->assertSame('1', $this->object->getHost());
    }

    public function testUser()
    {
        $this->assertNull($this->object->getUser());
        $this->object->setUser('1');
        $this->assertSame('1', $this->object->getUser());
    }

    public function testUseAgent()
    {
        $this->assertEquals(Task::STRING_FALSE, $this->object->getUseAgent());
        $this->assertFalse($this->object->getUseAgent(false));
        $this->object->setUseAgent(true);
        $this->assertSame(Task::STRING_TRUE, $this->object->getUseAgent());
        $this->assertTrue($this->object->getUseAgent(false));
    }
}
