<?php

namespace Pheanstalk\Structure;

use PHPUnit\Framework\TestCase;

class TaskInstanceTest extends TestCase
{

    /** @var TaskInstance $object */
    protected $object;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->object = new TaskInstance([]);
    }

    public function testContextId()
    {
        $this->object->setContextId(1);
        $this->assertSame(1, $this->object->getContextId());
    }

    public function testEvqid()
    {
        $this->object->setEvqid(1);
        $this->assertSame(1, $this->object->getEvqid());
    }

    public function testExecutionTime()
    {
        $date = new \DateTime();
        $this->object->setExecutionTime($date);
        $this->assertSame($date, $this->object->getExecutionTime());
    }

    public function testPid()
    {
        $this->object->setPid(1);
        $this->assertSame(1, $this->object->getPid());
    }

    public function testProgression()
    {
        $this->object->setProgression(1);
        $this->assertSame(1, $this->object->getProgression());
    }

    public function testStatus()
    {
        $this->object->setStatus('1');
        $this->assertSame('1', $this->object->getStatus());
    }

    public function testTid()
    {
        $this->object->setTid(1);
        $this->assertSame(1, $this->object->getTid());
    }

}
