FROM debian:stretch
ENV TZ=Europe/Paris
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y build-essential cmake git libmariadbclient-dev libgit2-dev libxerces-c-dev libpcre++-dev openssh-server
RUN git clone https://github.com/coldsource/evqueue-core.git
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata
WORKDIR /evqueue-core
RUN mkdir build
WORKDIR /evqueue-core/build
RUN cmake ..
RUN make
COPY evqueue.conf /etc
RUN groupadd evqueue
RUN useradd -m -g evqueue evqueue
RUN mkdir /home/evqueue/.ssh
RUN ssh-keygen -q -t rsa -N '' -f /home/evqueue/.ssh/id_rsa
RUN chown -R evqueue:evqueue /home/evqueue
RUN apt-get remove -y --purge build-essential cmake
RUN apt-get autoremove -y --purge
CMD /evqueue-core/build/evqueue --config /etc/evqueue.conf
EXPOSE 5000
